const Countries = [
  { key: 'Algeria', text: 'Algeria', value: 'Algeria' },
  { key: 'Austria', text: 'Austria', value: 'Austria' },
  { key: 'Belarus', text: 'Belarus', value: 'Belarus' },
  { key: 'Botswana', text: 'Botswana', value: 'Botswana' },
  { key: 'Chile', text: 'Chile', value: 'Chile' },
  { key: 'Dominican Republic', text: 'Dominican Republic', value: 'Dominican Republic' },
  { key: 'El Salvador', text: 'El Salvador', value: 'El Salvador' },
  { key: 'Fiji', text: 'Fiji', value: 'Fiji' },
  { key: 'Greece', text: 'Greece', value: 'Greece' },
  { key: 'Honduras', text: 'Honduras', value: 'Honduras' },
  { key: 'Indonesia', text: 'Indonesia', value: 'Indonesia' },
  { key: 'Italy', text: 'Italy', value: 'Italy' },
  { key: 'Jamaica', text: 'Jamaica', value: 'Jamaica' },
  { key: 'Kazakhstan', text: 'Kazakhstan', value: 'Kazakhstan' },
  { key: 'Latvia', text: 'Latvia', value: 'Latvia' },
  { key: 'Mexico', text: 'Mexico', value: 'Mexico' },
  { key: 'Morocco', text: 'Morocco', value: 'Morocco' },
  { key: 'Nepal', text: 'Nepal', value: 'Nepal' },
  { key: 'New Zealand', text: 'New Zealand', value: 'New Zealand' },
  { key: 'Oman', text: 'Oman', value: 'Oman' },
  { key: 'Poland', text: 'Poland', value: 'Poland' },
  { key: 'Portugal', text: 'Portugal', value: 'Portugal' },
  { key: 'Qatar', text: 'Qatar', value: 'Qatar' },
  { key: 'Russian Federation', text: 'Russian Federation', value: 'Russian Federation' },
  { key: 'Senegal', text: 'Senegal', value: 'Senegal' },
  { key: 'Slovenia', text: 'Slovenia', value: 'Slovenia' },
  { key: 'South Africa', text: 'South Africa', value: 'South Africa' },
  { key: 'Spain', text: 'Spain', value: 'Spain' },
  { key: 'Sweden', text: 'Sweden', value: 'Sweden' },
  { key: 'Taiwan', text: 'Taiwan', value: 'Taiwan' },
  { key: 'Tunisia', text: 'Tunisia', value: 'Tunisia' },
  { key: 'Uganda', text: 'Uganda', value: 'Uganda' },
  { key: 'United Kingdom', text: 'United Kingdom', value: 'United Kingdom' },
  { key: 'United States', text: 'United States', value: 'United States' },
  { key: 'Venezuela', text: 'Venezuela', value: 'Venezuela' },
  { key: 'Zambia', text: 'Zambia', value: 'Zambia' },
  { key: 'Zimbabwe', text: 'Zimbabwe', value: 'Zimbabwe' }
];

export default Countries;
